--- # setup DNS on the Ansible node
- hosts: localhost
  connection: local
  gather_facts: smart
  become: yes
  user: scotty
  tasks:
    - name: Install bind software and some others
      yum: state=latest update_cache=yes pkg={{ item }}
      with_items:
        - bind
        - bind-utils
        - python-dns
        - tree
        - net-tools
        - NetworkManager-tui
        - vim-enhanced
        - yum-utils
        - deltarpm
    - name: Run a yum update
      yum: state=latest update_cache=yes pkg=*
      
    - name: "Add trusted zone IPs to named.conf"
      blockinfile:
        state: present
        path: /etc/named.conf
        backup: yes
        insertafter: "acl "trusted" {"
        marker: "# {mark} Ansible managed "
        block: |
          {{ ansibledns_ip }}
          {{ rhv1_ip }}
          {{ rhv2_ip }}
          {{ glstr1_ip }}
          {{ glstr2_ip }}
          {{ glstr2_ip }}
        validate: '/usr/sbin/named-checkconf %s'
        
    - name: "Add IP of our DNS to named.conf"
      lineinfile:
        path: /etc/named.conf
        state: present
        #note the variable here for the ansible host ip address
        line: "listen-on port 53 { 127.0.0.1; "{{ ansible_ip_address }}"; };"
        validate: '/usr/sbin/named-checkconf %s'
        
    - name: "Change allow-query to 'trusted' in named.conf"
      lineinfile:
        path: /etc/named.conf
        state: present
        line: "allow_query { trusted; };"
        validate: '/usr/sbin/named-checkconf %s'
        
    - name: "Add include for named.conf.local"
      lineinfile:
        path: /etc/named.conf
        state: present
        insertafter: EOF
        line: "include "/etc/named/named.conf.local";"
        validate: '/usr/sbin/named-checkconf %s'
    - name: Add entries to resolv.conf
      blockinfile:
        path: /etc/resolv.conf
        block: |
          search 2rhv.com
          nameserver {{ ansibledns_ip }}
        insertafter: EOF
        state: present
        
#    - name: Attempt a DNS query
#      debug: msg="This host queries the DNS properly"
#      when: lookup('dig', 'ansible-cm') == 
        
#    - name: Assert that DNS query
#      assert: 
#        that: { ? }
#        msg: Still unable to query the correct DNS server.

# Now Configure the local named file
    
    - name: Create and add zones into named.conf.local
      template:
        src: named.conf.local.j2
        dest: /etc/named/named.conf.local

# Create zones folder
    - name: "mkdir /etc/named/zones -p"
      file: path=/etc/named/zones state=directory mode=0755

# Now create the fwd and rev zone files..

    - name: Create forward zone from template
      template:
        src: db.domain.fwd-zone.j2
        dest: "/etc/named/zones/db.{{ my_domain }}"
        mode: 0755
        
    - name: Create reverse zone from template
        template:
        src: db.subnet.rev-zone.j2
        dest: "/etc/named/zones/db.{{ subnetrev }}"
        
